require("huseyin.plugins-setup")

require("huseyin.core.options")
require("huseyin.core.autocmd")
require("huseyin.core.keymaps")
require("huseyin.core.colorscheme")

require("huseyin.plugins.treesitter")
require("huseyin.plugins.comment")
require("huseyin.plugins.nvim-tree")
require("huseyin.plugins.lualine")
require("huseyin.plugins.telescope")
require("huseyin.plugins.nvim-cmp")
require("huseyin.plugins.lsp.mason")
require("huseyin.plugins.lsp.lspsaga")
require("huseyin.plugins.lsp.lspconfig")
require("huseyin.plugins.lsp.null-ls")
require("huseyin.plugins.lsp.lspsignature")
require("huseyin.plugins.lsp.lsp-lines")
require("huseyin.plugins.autopairs")
require("huseyin.plugins.gitsigns")
require("huseyin.plugins.bufferline")
require("huseyin.plugins.vim-illuminate")
require("huseyin.plugins.vim-fugitive")
require("huseyin.plugins.nvim-ufo")
require("huseyin.plugins.which-key")
require("huseyin.plugins.nvim-navbuddy")
require("huseyin.plugins.trouble")
require("huseyin.plugins.code_runner")
require("huseyin.plugins.toggleterm")

require("huseyin.plugins.google_search")
